Revert files to 'orig'

diff --git a/tob b/tob
--- a/tob
+++ b/tob
@@ -197,7 +197,7 @@ checkenv ()
     
     if [ "$NEEDROOT" = "yes" ] ; then
 	if [ $UID -ne 0 ]; then
-	    error "You need to be root to run tob!"
+	    error "You need to be root to run tobs!"
 	fi
     fi
 }
@@ -218,9 +218,14 @@ readrc ()
     	error "BACKUPDIR is deprecated: check your config file, and rename it to BACKUPDEV"
     fi
 
-    if [ "$BACKUPDEV" = "" ]; then
-        BACKUPDEV="/var/lib/tob"
-	message "Using default backup device $BACKUPDEV"
+    if [ -d "$BACKUPDEV" ]; then
+    	BACKUPDIR=$BACKUPDEV
+    	BACKUPDEV="${BACKUPDIR}/${VOLUMENAME}_${DATE}_${TYPE}.${EXT}"
+    elif [ "$BACKUPDEV" = "" ]; then
+        BACKUPDIR="/var/lib/tob"
+    	BACKUPDEV="${BACKUPDIR}/${VOLUMENAME}_${DATE}_${TYPE}.${EXT}"
+    elif [ -f "$BACKUPDEV" -o ! -e "$BACKUPDEV" ]; then
+        BACKUPDIR=`dirname $BACKUPDEV`
     fi
 
     # check that relevant environment vars are set
@@ -347,17 +352,16 @@ makefulllist ()
     #fi
     #		       'findswitch' also removed from the paragraph after next
 
-  cat $TOBHOME/volumes/$1.startdir | \
-  xargs -i $nicefindcmd find {} $xdevflag  -printf '%p'$S'[ctime:] %C@ [owner/group:]  %u:%g' \( \( -fstype fat -or -fstype vfat \) -and -printf ' [mtime:] %T@' -or -printf ' [inode:] %i' \) -printf ' [linkto:] %l [perm:] %m [hardlinks:] %n\n' | \
+  $nicefindcmd find `cat $TOBHOME/volumes/$1.startdir` $xdevflag  -printf '%p'$S'[ctime:] %C@ [owner/group:]  %u:%g' \( \( -fstype fat -or -fstype vfat \) -and -printf ' [mtime:] %T@' -or -printf ' [inode:] %i' \) -printf ' [linkto:] %l [perm:] %m [hardlinks:] %n\n' | \
 	sed -e 's.\\.\\\\.g' | \
 	# If the exclude file contains non-blank lines, filter against it.
 	# If it is empty, or doesn't exist, just cat stdin to stdout
 	if grep -q -s . $TOBHOME/volumes/$1.exclude ; then
-	    grep -v -f$TOBHOME/volumes/$1.exclude --binary-files=text
+	    grep -v -f$TOBHOME/volumes/$1.exclude
 	else
 	    cat
 	fi |
-	sort -u > $TMPLIST || \
+	sort > $TMPLIST || \
 	    error "list creation failed."
 
         grep -q . $TMPLIST ||
@@ -436,7 +440,7 @@ calcdeletions()
 searchlistings ()
 {
     cd $TOBLISTS || error "$TOBLISTS directory is missing."
-    files=`$LS -1t | $GREP -v _deletions$`
+    files=`$LS -1 | $GREP -v _deletions$`
 
     if [ "$files" = "" ] ; then
 	message "No backups were made."
@@ -473,14 +477,14 @@ countbackup ()
     else
 	sed -e 's.\\\\.\\.g' -e "$SEDNAMESCRIPT" < "$1" > $FILELIST
 	eval "$BACKUPCMDTOSTDOUT" |
-           wc -c |
-           awk '{ if ($1 < 1000)
-                       printf ("Estimated: %d bytes\n",$1);
-                  else if ($1 < 1000000)
-                       printf ("Estimated: %.1f KB\n",$1/1000.0);
-                   else
-                       printf ("Estimated: %.1f MB\n",$1/1000000.0); }' \
-	   || error "backup size estimate failed."
+	    wc |
+	    awk '{ if ($3 < 1000)
+		        printf ("Estimated: %d bytes\n",$3); 
+	           else if ($3 < 1000000)
+			printf ("Estimated: %.1f KB\n",$3/1000.0); 
+	           else
+			printf ("Estimated: %.1f MB\n",$3/1000000.0); }' \
+	    || error "backup size estimate failed."
     fi
 }
 
@@ -493,14 +497,9 @@ countbackup ()
 runverify ()
 {
     VOLUMENAME=$2		     # store name for usage in .rc file
-
-    if [ -d "$BACKUPDEV" ]; then
-        BACKUPDEV=(`$LS ${BACKUPDEV}/${VOLUMENAME}_*full.${EXT}`)
-        if [ ${#BACKUPDEV[*]} -ne 1 ]; then
-            error "More than one full backup to choose from.  Use -f to select one."
-        fi
+    if [ -d "$BACKUPDIR" ]; then
+	BACKUPDEV=`$LS ${BACKUPDIR}/${VOLUMENAME}_*Full.${EXT}`
     fi
-
     message "Now starting verify program for $BACKUPDEV."
     ( cd /;
       eval "$VERIFYCMD" 
@@ -513,9 +512,6 @@ runverify ()
 runbackup ()
 {
     VOLUMENAME=$2	# store name for usage in .rc file
-    if [ -d "$BACKUPDEV" ]; then
-    	BACKUPDEV="${BACKUPDEV}/${VOLUMENAME}_${DATE}_${TYPE}.${EXT}"
-    fi
     
     message "Now starting backup program to write to $BACKUPDEV."
     sed -e 's.\\\\.\\.g' -e "$SEDNAMESCRIPT" < "$1" > $FILELIST
@@ -557,9 +553,9 @@ listvolumes ()
 	exclude=$base.exclude
 
 	echo "Volume \"$base\""
-	echo "    starts:   " `cat $f`
+	message "    starts:   " `cat $f`
 	if [ -f $exclude ] ; then
-	    echo "    excludes: " `cat $exclude`
+	    message "    excludes: " `cat $exclude`
 	fi
     done
 }
@@ -580,14 +576,12 @@ findfile ()
 
 deleteoldbackups ()
 {
-    # Since runbackups has run, $BACKUPDEV is either a file or a device.
-    # We only do deletions when it is a file.
-    if [ "$MAXBACKUPAGE" -ge 0 -a -f "$BACKUPDEV" ]; then
+    if [ -d "$BACKUPDIR" -a "$MAXBACKUPAGE" -ge 0 ]; then
 	UPTO=`basename $BACKUPDEV`
-	cd `dirname $BACKUPDEV`
-	message "Deleting old backups from `dirname $BACKUPDEV`:"
+	cd $BACKUPDIR
+	message "Deleting old backups:"
 	PR=""; [ "$VERBOSE" == "yes" ] && PR="-print"
-	find . -regex ./${VOLUMENAME}_'.*\('$1'\).*' -type f -mtime +$MAXBACKUPAGE ! -name "$UPTO" -exec $RM -f {} \; $PR
+	find . -regex ./${VOLUMENAME}_'.*\('$1'\).*' -type f -maxdepth 1 -mtime +$MAXBACKUPAGE ! -name "$UPTO" -exec $RM -f {} \; $PR
     fi
 }
 
@@ -697,13 +691,15 @@ inccount ()
 # generate listing of stuff on backup device
 verbose ()
 {
-    message "Generating report of $BACKUPDEV."
-    if [ -d "$BACKUPDEV" ]; then
-      for i in `$LS ${BACKUPDEV}/*.${EXT}`; do
+
+    if [ -d "$BACKUPDIR" ]; then
+      message "Generating report of $BACKUPDIR."
+      for i in `$LS ${BACKUPDIR}/*`; do
       	BACKUPDEV=$i
 	eval "$LISTCMD"
       done
     else
+      message "Generating report of $BACKUPDEV."
       eval "$LISTCMD" || error "listing of $BACKUPDEV cannot be generated."
     fi
 }
@@ -722,8 +718,8 @@ restore ()
     FILESPEC=$3
     message "Restoring volume $VOLUMENAME files matching $FILESPEC into $startdir."
 
-    if [ -d "$BACKUPDEV" ]; then
-       for i in `$LS ${BACKUPDEV}/${VOLUMENAME}_*.${EXT}`; do
+    if [ -d "$BACKUPDIR" ]; then
+       for i in `$LS ${BACKUPDIR}/${VOLUMENAME}_*.${EXT}`; do
           BACKUPDEV=$i
 	  eval "$RESTORECMD" && message "restored data from $i"
        done
